<a href="https://colab.research.google.com/github/sagarkakkar03/MachineLearning/blob/main/MelbornModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('melb_data.csv')
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [6]:
df.Suburb.unique()

array(['Abbotsford', 'Airport West', 'Albert Park', 'Alphington',
       'Altona', 'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton',
       'Ashwood', 'Avondale Heights', 'Balaclava', 'Balwyn',
       'Balwyn North', 'Bentleigh', 'Bentleigh East', 'Box Hill',
       'Braybrook', 'Brighton', 'Brighton East', 'Brunswick',
       'Brunswick West', 'Bulleen', 'Burwood', 'Camberwell', 'Canterbury',
       'Carlton North', 'Carnegie', 'Caulfield', 'Caulfield North',
       'Caulfield South', 'Chadstone', 'Clifton Hill', 'Coburg',
       'Coburg North', 'Collingwood', 'Doncaster', 'Eaglemont',
       'Elsternwick', 'Elwood', 'Essendon', 'Essendon North', 'Fairfield',
       'Fitzroy', 'Fitzroy North', 'Flemington', 'Footscray', 'Glen Iris',
       'Glenroy', 'Gowanbrae', 'Hadfield', 'Hampton', 'Hampton East',
       'Hawthorn', 'Heidelberg Heights', 'Heidelberg West', 'Hughesdale',
       'Ivanhoe', 'Kealba', 'Keilor East', 'Kensington', 'Kew',
       'Kew East', 'Kooyong', 'Maidstone', 'Malvern', 'Malvern East',
       'Maribyrnong', 'Melbourne', 'Middle Park', 'Mont Albert',
       'Moonee Ponds', 'Moorabbin', 'Newport', 'Niddrie',
       'North Melbourne', 'Northcote', 'Oak Park', 'Oakleigh South',
       'Parkville', 'Pascoe Vale', 'Port Melbourne', 'Prahran', 'Preston',
       'Reservoir', 'Richmond', 'Rosanna', 'Seddon', 'South Melbourne',
       'South Yarra', 'Southbank', 'Spotswood', 'St Kilda', 'Strathmore',
       'Sunshine', 'Sunshine North', 'Sunshine West', 'Surrey Hills',
       'Templestowe Lower', 'Thornbury', 'Toorak', 'Viewbank', 'Watsonia',
       'West Melbourne', 'Williamstown', 'Williamstown North', 'Windsor',
       'Yallambie', 'Yarraville', 'Aberfeldie', 'Bellfield',
       'Brunswick East', 'Burnley', 'Campbellfield', 'Carlton',
       'East Melbourne', 'Essendon West', 'Fawkner', 'Hawthorn East',
       'Heidelberg', 'Ivanhoe East', 'Jacana', 'Kingsbury', 'Kingsville',
       'Murrumbeena', 'Ormond', 'West Footscray', 'Albion', 'Brooklyn',
       'Glen Huntly', 'Oakleigh', 'Ripponlea', 'Cremorne', 'Docklands',
       'South Kingsville', 'Strathmore Heights', 'Travancore',
       'Caulfield East', 'Seaholme', 'Keilor Park', 'Gardenvale',
       'Princes Hill', 'Bayswater', 'Bayswater North', 'Beaumaris',
       'Berwick', 'Boronia', 'Briar Hill', 'Broadmeadows', 'Bundoora',
       'Burnside Heights', 'Burwood East', 'Cairnlea', 'Caroline Springs',
       'Cheltenham', 'Craigieburn', 'Cranbourne', 'Croydon', 'Dandenong',
       'Dandenong North', 'Diamond Creek', 'Dingley Village',
       'Doncaster East', 'Donvale', 'Doreen', 'Eltham', 'Epping',
       'Forest Hill', 'Frankston', 'Frankston North', 'Frankston South',
       'Gisborne', 'Gladstone Park', 'Greensborough', 'Hallam',
       'Healesville', 'Highett', 'Hillside', 'Huntingdale',
       'Keilor Downs', 'Keilor Lodge', 'Keysborough', 'Kings Park',
       'Lalor', 'Lower Plenty', 'Melton', 'Mernda', 'Mill Park',
       'Mitcham', 'Montmorency', 'Mordialloc', 'Mount Waverley',
       'Narre Warren', 'Nunawading', 'Oakleigh East', 'Parkdale',
       'Point Cook', 'Ringwood East', 'Rockbank', 'Rowville',
       'Sandringham', 'Seaford', 'Skye', 'South Morang', 'Springvale',
       'St Albans', 'Sunbury', 'Tarneit', 'Taylors Hill', 'Taylors Lakes',
       'The Basin', 'Thomastown', 'Truganina', 'Tullamarine', 'Vermont',
       'Wantirna', 'Wantirna South', 'Werribee', 'Westmeadows',
       'Williams Landing', 'Wollert', 'Wyndham Vale', 'Black Rock',
       'Blackburn', 'Blackburn North', 'Bonbeach', 'Carrum', 'Chelsea',
       'Clayton', 'Doveton', 'Ferntree Gully', 'Glen Waverley',
       'Greenvale', 'Heathmont', 'Hoppers Crossing', 'McKinnon',
       'Melton South', 'Melton West', 'Mentone', 'Mooroolbark',
       'Mulgrave', 'Ringwood', 'Roxburgh Park', 'Seabrook', 'Templestowe',
       'Vermont South', 'Warrandyte', 'Watsonia North', 'Wheelers Hill',
       'Altona Meadows', 'Blackburn South', 'Carrum Downs',
       'Clayton South', 'Croydon North', 'Langwarrin', 'Noble Park',
       'Notting Hill', 'Ringwood North', 'Sydenham', 'Albanvale',
       'Beaconsfield Upper', 'Chelsea Heights', 'Dallas', 'Deer Park',
       'Eltham North', 'Keilor', 'Meadow Heights', 'Mount Evelyn',
       'North Warrandyte', 'Pakenham', 'Riddells Creek', 'Sandhurst',
       'Scoresby', 'Silvan', 'Aspendale', 'Chirnside Park',
       'Croydon Hills', 'Croydon South', 'Derrimut', 'Diggers Rest',
       'Edithvale', 'Hampton Park', 'Knoxfield', 'St Helena', 'Upwey',
       'Bacchus Marsh', 'Coolaroo', 'Cranbourne North', 'Kilsyth',
       'Montrose', 'Aspendale Gardens', 'Bullengarook', 'Clarinda',
       'Deepdene', 'Delahey', 'Hurstbridge', 'Kurunjang', 'Wonga Park',
       'Endeavour Hills', 'Officer', 'Waterways', 'Ardeer',
       'Beaconsfield', 'Springvale South', 'Yarra Glen', 'Brookfield',
       'Emerald', 'Whittlesea', 'Burnside', 'Attwood', 'Wallan',
       'New Gisborne', 'Plumpton', 'Monbulk'], dtype=object)

In [9]:
df.Regionname.unique()

array(['Northern Metropolitan', 'Western Metropolitan',
       'Southern Metropolitan', 'Eastern Metropolitan',
       'South-Eastern Metropolitan', 'Eastern Victoria',
       'Northern Victoria', 'Western Victoria'], dtype=object)

In [10]:
len(df.CouncilArea.unique())

34

In [7]:
df.Type.unique()

array(['h', 'u', 't'], dtype=object)

In [8]:
df.corr(columns=[])

ValueError: could not convert string to float: 'Abbotsford'

In [14]:
df.drop(columns = ['Suburb', 'Address', 'Method', 'Date', 'SellerG', 'CouncilArea', 'Lattitude', 'Longtitude', 'BuildingArea', 'YearBuilt'], inplace=True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rooms          13580 non-null  int64
 1   Type           13580 non-null  object
 2   Price          13580 non-null  float64
 3   Distance       13580 non-null  float64
 4   Postcode       13580 non-null  float64
 5   Bedroom2       13580 non-null  float64
 6   Bathroom       13580 non-null  float64
 7   Car            13518 non-null  float64
 8   Landsize       13580 non-null  float64
 9   Regionname     13580 non-null  object
 10  Propertycount  13580 non-null  float64
dtypes: float64(8), int64(1), object(2)
memory usage: 1.1+ MB

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
ohe = OneHotEncoder(sparse_output=False)
ohe_Type = ohe.fit_transform(df[['Type']])

In [29]:
type_column_names = ohe.get_feature_names_out(['Type'])
df_type_encoded = pd.DataFrame(ohe_Type, columns=type_column_names, index=df.index)
df_type_encoded

       Type_h  Type_t  Type_u
0         1.0     0.0     0.0
1         1.0     0.0     0.0
2         1.0     0.0     0.0
3         1.0     0.0     0.0
4         1.0     0.0     0.0
...       ...     ...     ...
13575     1.0     0.0     0.0
13576     1.0     0.0     0.0
13577     1.0     0.0     0.0
13578     1.0     0.0     0.0
13579     1.0     0.0     0.0

[13580 rows x 3 columns]

In [30]:
df = pd.concat([df.drop('Type', axis=1), df_type_encoded], axis=1)
print(df.head())

   Rooms      Price  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  \
0      2  1480000.0       2.5    3067.0       2.0       1.0  1.0     202.0
1      2  1035000.0       2.5    3067.0       2.0       1.0  0.0     156.0
2      3  1465000.0       2.5    3067.0       3.0       2.0  0.0     134.0
3      3   850000.0       2.5    3067.0       3.0       2.0  1.0      94.0
4      4  1600000.0       2.5    3067.0       3.0       1.0  2.0     120.0

              Regionname  Propertycount  Type_h  Type_t  Type_u
0  Northern Metropolitan         4019.0     1.0     0.0     0.0
1  Northern Metropolitan         4019.0     1.0     0.0     0.0
2  Northern Metropolitan         4019.0     1.0     0.0     0.0
3  Northern Metropolitan         4019.0     1.0     0.0     0.0
4  Northern Metropolitan         4019.0     1.0     0.0     0.0

In [31]:
ohe_Region = ohe.fit_transform(df[['Regionname']])

In [32]:
region_column_names = ohe.get_feature_names_out(['Regionname'])
df_region_encoded = pd.DataFrame(ohe_Region, columns=region_column_names, index=df.index)
df_region_encoded

,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
13575,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13576,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13577,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13578,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13579,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [33]:
df['Car'].fillna(1, inplace=True)

/tmp/ipykernel_9839/3504053072.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Car'].fillna(1, inplace=True)

In [34]:
df.isnull().sum()

Rooms            0
Price            0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
Regionname       0
Propertycount    0
Type_h           0
Type_t           0
Type_u           0
dtype: int64

In [37]:
final_df = pd.concat([df.drop(['Regionname'], axis=1), df_region_encoded], axis = 1)

In [38]:
final_df.head()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Propertycount,Type_h,Type_t,Type_u,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
0,2,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.0,4019.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.0,4019.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,3,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,4019.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,3,850000.0,2.5,3067.0,3.0,2.0,1.0,94.0,4019.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,4,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,4019.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0